// Code generated by scratch. You must modify it.

package balancerservice

import (
	desc "github.com/yasamprom/cdn-balancer/internal/pb/api"
)

type Implementation struct {
	desc.UnimplementedBalancerServer
	uc usecases
}

type Config struct {
	Usecases usecases
}

// NewBalancerService return new instance of Implementation.
func NewBalancerService(cfg *Config) *Implementation {
	return &Implementation{
		uc: cfg.Usecases,
	}
}
